Sandbox logs:
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"bd4ac404-0d75-4eb5-bd56-3e4be80a7606\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"bd4ac404-0d75-4eb5-bd56-3e4be80a7606\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 0
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"e61d2f97-76a0-45fc-8891-47c999887401\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"e61d2f97-76a0-45fc-8891-47c999887401\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"427e2f6f-cf1f-49de-b5a0-f7f9fe79fe92\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"427e2f6f-cf1f-49de-b5a0-f7f9fe79fe92\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"78377c78-dd62-4921-b05e-1b3f241d0a2c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"78377c78-dd62-4921-b05e-1b3f241d0a2c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"200cd9bf-92ed-425f-8434-c2635717dec9\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"200cd9bf-92ed-425f-8434-c2635717dec9\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"113fd0e0-ccfb-47a3-942b-eb93576a7700\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"113fd0e0-ccfb-47a3-942b-eb93576a7700\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6d647bbf-2f6c-48c2-851d-a1cacf872e9d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6d647bbf-2f6c-48c2-851d-a1cacf872e9d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"51b8e711-51b8-4419-bd28-43fb0fa96b36\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"51b8e711-51b8-4419-bd28-43fb0fa96b36\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1bad8eb5-dea9-4b24-8591-3a6dea78f380\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1bad8eb5-dea9-4b24-8591-3a6dea78f380\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"09c6f08a-737e-492e-93c7-b963bf3e34f5\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"09c6f08a-737e-492e-93c7-b963bf3e34f5\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6df10fc9-7d69-4b70-9fb8-4433fb166b6f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6df10fc9-7d69-4b70-9fb8-4433fb166b6f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1000
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"0956805a-1ef1-4a82-a92c-694ca3e58ed5\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"0956805a-1ef1-4a82-a92c-694ca3e58ed5\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9b22b9af-d1c5-4edc-8ba5-422b567a2695\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9b22b9af-d1c5-4edc-8ba5-422b567a2695\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"56ce7d09-dda7-4868-8ff9-b41e90fb80cc\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"56ce7d09-dda7-4868-8ff9-b41e90fb80cc\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1bd15f91-7944-4f78-9244-d52a5e3285a0\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1bd15f91-7944-4f78-9244-d52a5e3285a0\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"02d1c4e8-15dd-45c6-af12-d49e2da1a7e4\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"02d1c4e8-15dd-45c6-af12-d49e2da1a7e4\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d52783ee-dffa-4ef1-856d-d08e83670ba8\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d52783ee-dffa-4ef1-856d-d08e83670ba8\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"799b2413-d704-4d1f-a27c-27c769778f41\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"799b2413-d704-4d1f-a27c-27c769778f41\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"50479e75-d90a-4c05-8798-fe4b38f2b8fb\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"50479e75-d90a-4c05-8798-fe4b38f2b8fb\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"b86c22e8-f948-488e-abdb-6ff6f6897987\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"b86c22e8-f948-488e-abdb-6ff6f6897987\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 1900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"c0d1c040-2dbb-418b-8375-a226d07d1862\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"c0d1c040-2dbb-418b-8375-a226d07d1862\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2000
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7c9ccd3f-53a1-4eb4-a484-1ea34fb08adb\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7c9ccd3f-53a1-4eb4-a484-1ea34fb08adb\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"aea05f81-58d9-4d90-9f18-5a5bbfc4edda\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"aea05f81-58d9-4d90-9f18-5a5bbfc4edda\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"dd581e2d-755a-4ae1-aa26-d2c25558799e\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"dd581e2d-755a-4ae1-aa26-d2c25558799e\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"170b61d9-980c-410c-b0fd-4c9a3307823f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"170b61d9-980c-410c-b0fd-4c9a3307823f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"f13d5759-55fa-40c7-be9c-bf2eba9d0305\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"f13d5759-55fa-40c7-be9c-bf2eba9d0305\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"099f4c4d-4310-43f8-8aec-89f316f09427\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"099f4c4d-4310-43f8-8aec-89f316f09427\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"28ab1fa1-959f-4057-899a-d5b0aabe8e1c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"28ab1fa1-959f-4057-899a-d5b0aabe8e1c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"94ad6a8a-ab13-4c40-bc87-bc76f8524a0f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"94ad6a8a-ab13-4c40-bc87-bc76f8524a0f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1c932181-eb2e-4b97-87b9-f3e89265bee7\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1c932181-eb2e-4b97-87b9-f3e89265bee7\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 2900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"ea023287-f14c-485e-b676-d7821852267c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"ea023287-f14c-485e-b676-d7821852267c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3000
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"2c3a6c11-6839-4943-98d4-d7b53094a988\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"2c3a6c11-6839-4943-98d4-d7b53094a988\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d670f87b-d3a1-4145-86d9-92816cbc531f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d670f87b-d3a1-4145-86d9-92816cbc531f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"5a695fc6-c097-4582-8694-1005f94dc76b\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"5a695fc6-c097-4582-8694-1005f94dc76b\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"a6dd5b5a-19bb-4a40-84b9-d970422b2a8a\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"a6dd5b5a-19bb-4a40-84b9-d970422b2a8a\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6ecdfe12-3da0-446e-93d2-f694f81e59bc\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6ecdfe12-3da0-446e-93d2-f694f81e59bc\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"bc7403d4-270e-4496-b334-3b86de4e808c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"bc7403d4-270e-4496-b334-3b86de4e808c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"e03a7533-a57e-4fbc-906a-eb2e6830758e\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"e03a7533-a57e-4fbc-906a-eb2e6830758e\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"c27330ab-9eaa-4662-9f51-a6c2cac25784\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"c27330ab-9eaa-4662-9f51-a6c2cac25784\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"b78e5210-856f-4e62-8135-624cae27a535\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"b78e5210-856f-4e62-8135-624cae27a535\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 3900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"0dd53d56-6fba-46c7-bab5-a6bf308a3cfc\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"0dd53d56-6fba-46c7-bab5-a6bf308a3cfc\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4000
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4c5ee75c-9e1c-441e-bd18-2b07eeab2cc6\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4c5ee75c-9e1c-441e-bd18-2b07eeab2cc6\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4a630de5-74bb-4d9d-8ffd-3ba8e8904277\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4a630de5-74bb-4d9d-8ffd-3ba8e8904277\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"2f510282-80de-4904-a75f-c610414f6a3d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"2f510282-80de-4904-a75f-c610414f6a3d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"19dc8876-14ad-4fe4-9fe7-b892fff97e18\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"19dc8876-14ad-4fe4-9fe7-b892fff97e18\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d03cc2cd-6e1b-40eb-a0fa-6abf6d944a17\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d03cc2cd-6e1b-40eb-a0fa-6abf6d944a17\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"00624b25-32e1-4353-8d58-f54ed9879378\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"00624b25-32e1-4353-8d58-f54ed9879378\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"118ed412-7494-412c-b690-ed54e60fb451\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"118ed412-7494-412c-b690-ed54e60fb451\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4e0e395a-6e99-4123-a6fa-4ba2ceaba1af\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4e0e395a-6e99-4123-a6fa-4ba2ceaba1af\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"23b73302-d99f-4eca-950c-b2ca1e0d7a3c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"23b73302-d99f-4eca-950c-b2ca1e0d7a3c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 4900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7b526709-e555-4b93-af73-b18d78647bca\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7b526709-e555-4b93-af73-b18d78647bca\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5000
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"5f7c2357-1270-47fc-98ef-ae3b48a95611\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"5f7c2357-1270-47fc-98ef-ae3b48a95611\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"399c6afd-ccc0-4456-9a00-28a5cf42dac3\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"399c6afd-ccc0-4456-9a00-28a5cf42dac3\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7de0d7b5-e49c-4025-8b0b-cae75155f80b\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7de0d7b5-e49c-4025-8b0b-cae75155f80b\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"0cc66e88-c015-4c47-b47a-b41a4ca638ef\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"0cc66e88-c015-4c47-b47a-b41a4ca638ef\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"06b105ac-ee77-443f-97be-f87e84186a08\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"06b105ac-ee77-443f-97be-f87e84186a08\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"a9673444-5b09-40b2-b799-857b4a309198\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"a9673444-5b09-40b2-b799-857b4a309198\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"fd6ac6c5-bd11-41f7-bcaf-d5464a6eacc6\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"fd6ac6c5-bd11-41f7-bcaf-d5464a6eacc6\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"15ee9a08-ba2c-4468-b36f-748951c1b0c6\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"15ee9a08-ba2c-4468-b36f-748951c1b0c6\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"21059f00-6b46-4f4c-84af-c0632841c458\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"21059f00-6b46-4f4c-84af-c0632841c458\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 5900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6f4e6156-c927-4303-8043-48c408674a25\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6f4e6156-c927-4303-8043-48c408674a25\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6000
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"f6618f05-b877-47cf-84ad-7c99166589ad\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"f6618f05-b877-47cf-84ad-7c99166589ad\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9c19ef47-402f-46c5-ae26-3d583a31df42\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9c19ef47-402f-46c5-ae26-3d583a31df42\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1a673da5-564d-47e6-96a8-42667acef39d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1a673da5-564d-47e6-96a8-42667acef39d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7c65df71-98e9-4716-b1c1-83317416fea2\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7c65df71-98e9-4716-b1c1-83317416fea2\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"a71c1038-6f65-495a-8242-46e5076f7ba0\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"a71c1038-6f65-495a-8242-46e5076f7ba0\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7c8083cb-2ed7-44af-827b-5e7e0f775467\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7c8083cb-2ed7-44af-827b-5e7e0f775467\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"66d7e9a5-dd95-461c-95b7-93483c4e5a06\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"66d7e9a5-dd95-461c-95b7-93483c4e5a06\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"78405665-485e-4fdd-856a-f9920e5dc8c6\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"78405665-485e-4fdd-856a-f9920e5dc8c6\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1990f469-8836-493f-8d3c-a559ab690b4d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1990f469-8836-493f-8d3c-a559ab690b4d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 6900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"65763e2b-3aba-4ad8-94e3-c875396c1d86\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"65763e2b-3aba-4ad8-94e3-c875396c1d86\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7000
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"419fdead-2f1d-44ea-b92c-703ad6b7b1e8\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"419fdead-2f1d-44ea-b92c-703ad6b7b1e8\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7bc5c59e-0d0a-42b0-b651-adb1e6fa8f17\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"7bc5c59e-0d0a-42b0-b651-adb1e6fa8f17\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"46581759-39e5-4cdc-8e43-1438e6ac2516\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"46581759-39e5-4cdc-8e43-1438e6ac2516\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"b85c6cdb-e1f0-4825-8b50-bbd7a210916c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"b85c6cdb-e1f0-4825-8b50-bbd7a210916c\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"61da3617-6a7a-4d91-8e87-b8ccfe4cab58\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"61da3617-6a7a-4d91-8e87-b8ccfe4cab58\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"26b94101-bf57-4364-bc93-f837763f0c1b\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"26b94101-bf57-4364-bc93-f837763f0c1b\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d931462d-35dd-44a9-b550-524ef8548346\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d931462d-35dd-44a9-b550-524ef8548346\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"8cd92bc7-4b71-4f37-b8bd-6adf70db797d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"8cd92bc7-4b71-4f37-b8bd-6adf70db797d\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"49376c3f-bb8a-49c7-ae3a-cb1e5368a0e8\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"49376c3f-bb8a-49c7-ae3a-cb1e5368a0e8\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 7900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1aeaac8b-da55-43b9-9317-6bc4201f89a1\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1aeaac8b-da55-43b9-9317-6bc4201f89a1\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8000
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"eeb8c004-36f0-4a14-8a94-6c2ec1c1ad6e\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"eeb8c004-36f0-4a14-8a94-6c2ec1c1ad6e\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"95c9b509-50cc-4b16-9875-a1d456bd9936\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"95c9b509-50cc-4b16-9875-a1d456bd9936\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4fe8e832-b98e-4f7c-9098-ea29c189ad4e\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4fe8e832-b98e-4f7c-9098-ea29c189ad4e\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9baa30a2-9e26-4768-8a46-b7876b6ad4fb\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9baa30a2-9e26-4768-8a46-b7876b6ad4fb\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4f49c156-a628-4d2c-b465-43b1eb689fda\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4f49c156-a628-4d2c-b465-43b1eb689fda\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"efb93c5d-b462-4e70-857f-58d17a092188\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"efb93c5d-b462-4e70-857f-58d17a092188\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1b9e4f64-0e4f-491f-84e7-c40ee9cfcd81\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"1b9e4f64-0e4f-491f-84e7-c40ee9cfcd81\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"02ba84c0-a9f4-414a-912a-602e35efaad9\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"02ba84c0-a9f4-414a-912a-602e35efaad9\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6c348539-b9c6-4af8-ac60-3458146c4f24\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"6c348539-b9c6-4af8-ac60-3458146c4f24\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 8900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9a5ba3a6-6341-44be-8950-900955115fb9\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9a5ba3a6-6341-44be-8950-900955115fb9\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9000
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9c6e7017-1bc2-44e5-8524-008002d0a4b5\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"9c6e7017-1bc2-44e5-8524-008002d0a4b5\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9100
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"01bd88fb-2f7d-4bf4-9519-e6656312239f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"01bd88fb-2f7d-4bf4-9519-e6656312239f\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9200
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"ac9e6e73-55ed-4a09-bef6-2aca9adf9720\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"ac9e6e73-55ed-4a09-bef6-2aca9adf9720\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9300
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d28d0759-552c-4f86-a0b4-fc06e001ee36\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"d28d0759-552c-4f86-a0b4-fc06e001ee36\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9400
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"863389b2-6fb1-4dc8-8338-a42d614d25b8\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"863389b2-6fb1-4dc8-8338-a42d614d25b8\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9500
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"3a2b53c7-1591-4eb4-8c40-5dbeedf0d041\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"3a2b53c7-1591-4eb4-8c40-5dbeedf0d041\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9600
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"f1274fa8-c093-40d0-96a8-0c5b79066675\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"f1274fa8-c093-40d0-96a8-0c5b79066675\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9700
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"a8948107-d572-4553-aa90-bf4ebbc69e74\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"a8948107-d572-4553-aa90-bf4ebbc69e74\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9800
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4c50963e-a50d-4567-aef6-32bb0d670c39\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"4c50963e-a50d-4567-aef6-32bb0d670c39\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 9900
}
{
  "sandboxLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"fb50b263-dd4a-43e3-a5ee-43818731bffd\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "lambdaLog": "{\"errorMessage\": \"cannot access local variable 'product' where it is not associated with a value\", \"errorType\": \"UnboundLocalError\", \"requestId\": \"fb50b263-dd4a-43e3-a5ee-43818731bffd\", \"stackTrace\": [\"  File \\\"/var/task/app.py\\\", line 31, in lambda_handler\\n    orders, conversion, traderData = trader.run(trading_state)\\n\", \"  File \\\"/var/task/trader.py\\\", line 16, in run\\n    means = {products[0]:5058.63895, product[1]:9999.99975} #Using data from day0\\n\"]}",
  "timestamp": 10000
}
{
  "sandboxLog": "Lambda errors have reached maximum value for submission 2c9360c2-344d-412c-9637-4417769f2a1d",
  "lambdaLog": null,
  "timestamp": 120787
}



Activities log:
day;timestamp;product;bid_price_1;bid_volume_1;bid_price_2;bid_volume_2;bid_price_3;bid_volume_3;ask_price_1;ask_volume_1;ask_price_2;ask_volume_2;ask_price_3;ask_volume_3;mid_price;profit_and_loss




Trade History:
null